spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

    druid:
      aop-patterns: com.futurebytedance.boot05webadmin.*  #springbean监控
      filters: stat,wall,slf4j  #所有开启的功能

      stat-view-servlet: #监控页配置
        enabled: true
        login-username: admin
        login-password: admin
        resetEnable: false

      web-stat-filter: #web监控
        enabled: true
        urlPattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'

      filter:
        stat: #sql监控
          slow-sql-millis: 1000
          logSlowSql: true
          enabled: true
        wall: #防火墙
          enabled: true
          config:
            drop-table-allow: false

  redis:
    client-type: jedis
    url: redis://localhost:6379
    jedis:
      pool:
        max-active: 10
  #    lettuce:
  #      pool:
  #        max-active: 10
  #        min-idle: 5

  #    filters: stat,wall
  #    max-active: 12
  #    type: com.zaxxer.hikari.HikariDataSource
  jdbc:
    template:
      query-timeout: 3

# 配置mybatis规则
mybatis:
  #  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

# management是所有actuator的配置
# management.endpoint.端点名.xxx 对某个端点的具体配置
management:
  endpoints:
    enabled-by-default: false # 默认开启所有端点 true
    web:
      exposure:
        include: '*' #以Web方式暴漏所有端点
  endpoint:
    health:
      show-details: ALWAYS
      enabled: true
    info:
      enabled: true
    beans:
      enabled: true