spring:
#  mvc:
#    static-path-pattern: /res/**
#
  resources:
    static-locations: [classpath:/haha/]
    add-mappings: true
    cache:
      period: 1000
  mvc:
    hiddenmethod:
      filter:
        enabled: true